### ISSUE TITLE
Papermerge.com docs site is broken

### ISSUE THREAD

**Issue by n8willis** [papermerge/documentation#4]
The URL (as used on the site) https://www.papermerge.com/docs is un-styled raw HTML but, more importantly, all of the links are broken. That's not an exaggeration. 404-broken links. TOC, internal-page, in-body content; all of them broken
![papermerge](https://user-images.githubusercontent.com/2192132/164645887-551c1e47-ea5d-4868-9318-36da8e645c03.png)
.

**Comment by ciur** [comment]
@n8willis thank you for heads up and for taking your time and creating a ticket with screenshot.

The problem is in missing slash at the end of url: instead of [https://www.papermerge.com/docs]( https://www.papermerge.com/docs) should be [ https://www.papermerge.com/docs/]( https://www.papermerge.com/docs/). Last URL renders correctly.

Yet another URL for accessing documentation is [https://docs.papermerge.io](https://docs.papermerge.io)

**Comment by ciur** [comment]
Fixed! The fix is deployed :) 
![broken-docs-url](https://user-images.githubusercontent.com/24827601/165159749-0fa498f8-b9b9-4373-913f-5f968efe0e69.gif)

**Comment by ciur** [comment]
homepage was redesigned. Now documentation's URL is [https://docs.papermerge.io](https://docs.papermerge.io)
